#!/bin/bash

# Copyright (c) 2021 Alejandro Elí. All rights reserved.
# This file is subject to the terms and conditions defined in
# the LICENSE file, which is part of this source code package.

# Usage: . $XSH_HOME/compile [clean] [-prod]

if [[ $0 == $BASH_SOURCE ]]; then
  echo "Do not run this file, source it instead." >&2
  exit 1
fi

command -v v &> /dev/null || {
  echo -e "\e[31mError\e[m: The \`v\` executable was not found"
  echo
  echo "  Are you sure you have properly installed V?"
  echo "  https://github.com/vlang/v#installing-v-from-source"
  echo
  return 1
}

if [ ! $XSH_HOME ]; then
  export XSH_HOME=$(dirname $BASH_SOURCE)
fi

case $1 in
  clean )
    rm -rf $XSH_HOME/bin &> /dev/null
    shift
    ;;
esac

if [[ ! -d $XSH_HOME/bin ]]; then
  mkdir $XSH_HOME/bin
fi

xsh::get_plu () {
  local Modules=$VMODULES
  case $Modules in
    *:* ) Modules=${VMODULES%%:*} ;;
     '' ) Modules=$HOME/.vmodules ;;
  esac
  local Target=$Modules/plu
  local GitURL=https://github.com/onerbs/plu
  if [[ ! -d $Target ]]; then
    echo "Installing module \"plu\" from $GitURL to $Target ..."
    git clone --depth 1 --quiet $GitURL $Target || {
      echo -e "\e[31mError\e[m: failed to clone the \`plu\` repository"
      echo
      echo "  Please, make sure you have \`git\` installed"
      echo "  and an active Internet connection"
      echo
      return 2
    }
  fi
}

xsh::compile () {
  local Tool Flag
  local Source=$XSH_HOME/src
  local Output=$XSH_HOME/bin
  local Errors=$XSH_HOME/$(date '+%y%m%d').log

  case $1 in
    -prod )
      Flag=$1
      shift
      ;;
  esac

  for Tool in $@; do
    if [[ -x $Output/$Tool ]]; then
      # Avoid wasting resources, skip re-compiling.
      continue
    fi
    v $Flag $Source/$Tool.v -o $Output/$Tool &> $Errors || {
      echo -e "\e[31mError\e[m: failed to compile $Tool.v"
      echo
      echo "  Please, open an issue and share the logs"
      echo "  log file: $Errors"
      echo
      echo "  https://github.com/onerbs/xsh/issues/new"
      echo
      return 1
    }
  done

  # At this point, there's no errors.
  rm $Errors &> /dev/null || :
}

xsh::get_plu || return
xsh::compile $1 xsh_{watch,doc,scan} || return

unset -f xsh::compile xsh::get_plu
