#!/bin/bash

# Copyright (c) 2021 Alejandro Elí. All rights reserved.
# This file is subject to the terms and conditions defined in
# the LICENSE file, which is part of this source code package.

if [[ $0 == $BASH_SOURCE ]]; then
  echo "Do not run this file, source it instead." >&2
  exit 1
fi

#! The root directory of XSH
export XSH_HOME=$(dirname $BASH_SOURCE)

if [[ ! $(ls -1 $XSH_HOME/bin 2> /dev/null) ]]; then
  # Delete bin folder if empty
  rm -r $XSH_HOME/bin &> /dev/null
fi

if [[ ! -d $XSH_HOME/bin ]]; then
  source $XSH_HOME/compile || {
    echo "Error: failed to compile the tools."
    echo
    return 1
  }
fi

#! Modify the PATH variable for the active shell,
#! so the tools are available during the session.
export PATH+=:$XSH_HOME/bin

xsh::iter () {
  #! Execute ACTION over ACTORS
  #+ ACTION ACTORS
  local Watching=$(xsh_watch)
  local Action=$1 Actor Dir
  while (( $# > 1 )); do shift
    for Dir in $Watching; do
      Actor=$Dir/$1
      if [[ -d $Actor ]]; then
        xsh::iter $Action $(xsh::inner $Actor)
        continue
      fi
      Actor=$Actor.sh
      if [[ -f $Actor ]]; then
        $Action $Actor
        continue
      fi
    done
  done
}

xsh::inner () {
  local Name Dir=$(basename $1)
  if [[ -f $1/$Dir.sh ]]; then
    echo $Dir/$Dir
  fi
  for Name in $(ls $1); do
    case $Name in
      $Dir.sh ) ;;
      * ) echo $Dir/${Name%.*} ;;
    esac
  done
}

xsh::iter source base lib put
